name: Build and deploy Python app to Azure Web App - iMarketPredict-Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: iMarketPredict-Backend
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests
      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pip install pytest
          pytest

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
          retention-days: 2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write       # Required for azure/login
      contents: read        # Required for checkout (if needed)

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_64BA493709F44F5799D5156E5A137A51 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_325606B97CF04129B19BB20CF2B224E5 }} 
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_877C93C8161A4191A9DCC31CE8795FC5}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
